services:
  db:
    image: pgvector/pgvector:pg17
    container_name: interms-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: interms
    volumes:
      - interms-postgres-data:/var/lib/postgresql/data

volumes:
  interms-postgres-data:
    name: interms-postgres-data