"""add article dynamics and embeddings

Revision ID: 325641083fb0
Revises: 2470d39a2cdb
Create Date: 2026-09-21 23:22:18.339301

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '325641083fb0'
down_revision: Union[str, Sequence[str], None] = '2470d39a2cdb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('dynamics', sa.JSON(), nullable=True))
    op.add_column('articles', sa.Column('embeddings', Vector(768), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('articles', 'embeddings')
    op.drop_column('articles', 'dynamics')
    # ### end Alembic commands ###
