"""changed embeddings to embedding

Revision ID: 7dcdc52319e0
Revises: 325641083fb0
Create Date: 2026-09-21 23:31:58.022165

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector

# revision identifiers, used by Alembic.
revision: str = '7dcdc52319e0'
down_revision: Union[str, Sequence[str], None] = '325641083fb0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('embedding', Vector(768), nullable=True))
    op.drop_column('articles', 'embeddings')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('embeddings', Vector(768), autoincrement=False, nullable=True))
    op.drop_column('articles', 'embedding')
    # ### end Alembic commands ###
